# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gravity
email: hemangsk@gmail.com
description: The Liberal Jekyll Theme
baseurl: /jekyll_demo
url: "https://israining.github.com/jekyll_demo/" # the base hostname & protocol for your site
twitter_username: hemang_kumar
github_username:  israining

# Build settings
markdown: kramdown
