baseurl: /jekyll_demo

# Site settings
title: Coding24h
email: zhangzhengyu@coding24h.com
description: The Liberal is Coding24h'Space
baseurl: /jekyll_demo
url: "https://israining.github.com/jekyll_demo/" # the base hostname & protocol for your site
twitter_username: yu478435363
github_username:  israining

# Build settings
markdown: kramdown
